# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from static import resource_rc  

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 601)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.menu_widget = QtWidgets.QWidget(parent=self.splitter)
        self.menu_widget.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_widget.setFont(font)
        self.menu_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(221, 239, 255);\n"
"border: none;")
        self.menu_widget.setObjectName("menu_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.menu_widget)
        self.gridLayout.setContentsMargins(4, 4, 4, 15)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(parent=self.menu_widget)
        self.toolBox.setStyleSheet("#toolBox{\n"
"    color: #fff;\n"
"}\n"
"\n"
"#toolBox::tab{\n"
" padding-left: 5px;\n"
" text-align: left;\n"
" border-radius: 2px;\n"
"}\n"
"\n"
"#toolBox::tab:selected{\n"
"    background-color: #2d9cdb;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#toolBox QPushButton{\n"
"    padding: 5 px 0px 5px 20px;\n"
"    text-align: left;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#toolBox QPushButton:hover{\n"
"    background-color: #85C1E9;\n"
"}\n"
"\n"
"#toolBox QPushButton:checked{\n"
"    background-color: #4398D8;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 142, 488))
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.page)
        self.pushButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.page)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/file-plus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_17.setIcon(icon1)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout.addWidget(self.pushButton_17)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/grid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 604, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/layers.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox.addItem(self.page, icon3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 142, 488))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 576, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/slack.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox.addItem(self.page_2, icon4, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 142, 488))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/eye.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/chrome.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_3.addWidget(self.pushButton_12)
        spacerItem2 = QtWidgets.QSpacerItem(20, 604, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/loader.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox.addItem(self.page_3, icon7, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.menu_widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 0, 1, 1)
        self.main_widget = QtWidgets.QWidget(parent=self.splitter)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("#tabWidget{\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::close-button{\n"
"    margin-left: 3px;\n"
"    \n"
"    image: url(:/icons/icons/x.svg)\n"
"}\n"
"\n"
"QTabBar::close-button:hover{\n"
"    margin-left: 3px;\n"
"    \n"
"    image: url(/icons/icons/x-circle.svg);\n"
"}")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.search_widget = QtWidgets.QWidget(parent=self.main_widget)
        self.search_widget.setStyleSheet("#search_widget{\n"
"    background-color: #ABB2B9;\n"
"}")
        self.search_widget.setObjectName("search_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.search_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.search_widget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_8.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/chevrons-left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_8.setIcon(icon8)
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        spacerItem3 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.search_frame = QtWidgets.QFrame(parent=self.search_widget)
        self.search_frame.setEnabled(True)
        self.search_frame.setStyleSheet("#search_frame{\n"
"    border: 1px solid #aa7e6f;\n"
"    border-radius: 15px;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#search_frame QPushButton{\n"
"    padding: 5px 5px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#search_frame QPushButton:pressed{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#search_frame QLineEdit{\n"
"    border: none;\n"
"}")
        self.search_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_frame)
        self.horizontalLayout.setContentsMargins(15, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.search_frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.search_frame)
        self.pushButton_9.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_9.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border:none;")
        self.pushButton_9.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/more-horizontal.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_9.setIcon(icon9)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.horizontalLayout_2.addWidget(self.search_frame)
        spacerItem4 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.user_label = QtWidgets.QLabel(parent=self.search_widget)
        self.user_label.setMinimumSize(QtCore.QSize(30, 30))
        self.user_label.setMaximumSize(QtCore.QSize(30, 30))
        self.user_label.setStyleSheet("#user_label{\n"
"    background-color: #fff;\n"
"    border: 1px solid #F2F4F4;\n"
"    padding: 5px 5px;\n"
"    border-radius: 15%;\n"
"}\n"
"\n"
"#user_label:hover{\n"
"    background-color: rgb(238, 238, 238);\n"
"}")
        self.user_label.setText("")
        self.user_label.setPixmap(QtGui.QPixmap(":/icons/icons/settings.svg"))
        self.user_label.setScaledContents(True)
        self.user_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.user_label.setObjectName("user_label")
        self.horizontalLayout_2.addWidget(self.user_label)
        self.gridLayout_2.addWidget(self.search_widget, 0, 0, 1, 1)
        self.settings_widget = QtWidgets.QWidget(parent=self.splitter)
        self.settings_widget.setStyleSheet("#settings_widget{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(221, 239, 255);\n"
"    border: none;\n"
"}\n"
"\n"
"#settings_widget QPushButton{\n"
"    padding: 5 px 0px 5px 20px;\n"
"    text-align: left;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#settings_widget QPushButton:hover{\n"
"    background-color: #85C1E9;\n"
"}\n"
"\n"
"#settings_widgetx QPushButton:checked{\n"
"    background-color: #4398D8;\n"
"}")
        self.settings_widget.setObjectName("settings_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.settings_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.settings_widget)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(221, 239, 255);\n"
"border: none;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.settings_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 187, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 3, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.settings_widget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_4.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.settings_widget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_4.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.settings_widget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_4.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.settings_widget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_4.addWidget(self.pushButton_16)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(-1)
        self.pushButton_8.toggled['bool'].connect(self.menu_widget.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Home"))
        self.pushButton_17.setText(_translate("MainWindow", "SPM Image Process"))
        self.pushButton_2.setText(_translate("MainWindow", "Image Labeling"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Main"))
        self.pushButton_3.setText(_translate("MainWindow", "IP 1"))
        self.pushButton_4.setText(_translate("MainWindow", "IP 2"))
        self.pushButton_5.setText(_translate("MainWindow", "IP 3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Image Process"))
        self.pushButton_6.setText(_translate("MainWindow", "Computer Vision"))
        self.pushButton_7.setText(_translate("MainWindow", "Visualize .XYZ"))
        self.pushButton_11.setText(_translate("MainWindow", "Add a plug-in!"))
        self.pushButton_12.setText(_translate("MainWindow", "Add another!"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "More Plug-ins"))
        self.pushButton_10.setText(_translate("MainWindow", "Quit"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6.6pt;\">Credits or somethin goes here</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
